import React, { useState, useEffect } from 'react';
import { 
  BrainCircuit, 
  Search, 
  ShieldCheck, 
  FileText, 
  Terminal, 
  Activity, 
  ArrowRight, 
  Sparkles, 
  Mail, 
  ChevronDown, 
  Check
} from 'lucide-react';

interface LandingPageProps {
  onLaunch: () => void;
}

export const LandingPage: React.FC<LandingPageProps> = ({ onLaunch }) => {
  const [isOpen, setIsOpen] = useState(false);
  const [activeFaq, setActiveFaq] = useState<number | null>(null);
  
  // Contact Form States
  const [email, setEmail] = useState('');
  const [message, setMessage] = useState('');
  const [isSubmitted, setIsSubmitted] = useState(false);

  // Close mobile menu on Escape key
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setIsOpen(false);
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, []);

  const handleContactSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!email.trim() || !message.trim()) return;
    setIsSubmitted(true);
    setTimeout(() => {
      setIsSubmitted(false);
      setEmail('');
      setMessage('');
    }, 4000);
  };

  const FAQS = [
    {
      q: "How does the multi-agent swarm prevent hallucinations?",
      a: "Our architecture leverages a specialized Critic Node that cross-checks all claims generated by researchers against retrieved source telemetry. If a claim lacks direct bibliographic support, the Critic rejects the draft and forces the Researcher to expand search boundaries."
    },
    {
      q: "What search infrastructure does the system leverage?",
      a: "The Researcher node utilizes Tavily Search API, specifically designed for LLMs, to retrieve structured, high-relevance web content, filtering out SEO garbage and bloated trackers."
    },
    {
      q: "Can I customize the agent topology?",
      a: "Yes. Our architecture supports importing custom node graphs, enabling you to add specialized legal reviewers, quantitative analysts, or database sync nodes."
    },
    {
      q: "Is the final report exportable?",
      a: "Absolutely. Once the Synthesizer node completes the research, the console renders a clean, publication-grade Markdown document with footnotes, exportable with one click."
    }
  ];

  return (
    <div className={`landing-stage ${isOpen ? 'is-open' : ''}`}>
      {/* Scoped CSS styles for ultimate visual polish and zero Tailwind bleeding */}
      <style dangerouslySetInnerHTML={{ __html: `
        .landing-stage {
          --stage-bg: #030303;
          --stage-ink: #f4f4f5;
          --stage-muted: #a1a1aa;
          --accent-purple: #8b5cf6;
          --accent-blue: #3b82f6;
          --accent-green: #10b981;
          --glass-bg: rgba(9, 9, 11, 0.7);
          --glass-border: rgba(255, 255, 255, 0.05);
          --glass-border-hover: rgba(255, 255, 255, 0.12);
          
          background-color: var(--stage-bg);
          color: var(--stage-ink);
          font-family: 'Manrope', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          position: fixed;
          inset: 0;
          width: 100vw;
          height: 100vh;
          overflow-y: auto;
          overflow-x: hidden;
          scroll-behavior: smooth;
          z-index: 9999;
        }

        /* Fluid layout styling and glassmorphism elements */
        .landing-stage .obsidian-grid {
          background-size: 60px 60px;
          background-image: 
            linear-gradient(to right, rgba(255, 255, 255, 0.01) 1px, transparent 1px),
            linear-gradient(to bottom, rgba(255, 255, 255, 0.01) 1px, transparent 1px);
          position: relative;
        }

        .landing-stage .spotlight {
          position: absolute;
          width: 800px;
          height: 800px;
          background: radial-gradient(circle, rgba(139, 92, 246, 0.05) 0%, transparent 70%);
          pointer-events: none;
          z-index: 0;
          filter: blur(100px);
        }

        .landing-stage header.top-nav {
          position: fixed;
          top: 0;
          left: 0;
          right: 0;
          height: 72px;
          background: rgba(3, 3, 3, 0.6);
          backdrop-filter: blur(16px);
          -webkit-backdrop-filter: blur(16px);
          border-bottom: 1px solid var(--glass-border);
          z-index: 1000;
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 0 40px;
        }

        @media (max-width: 768px) {
          .landing-stage header.top-nav {
            padding: 0 20px;
          }
        }

        .landing-stage .logo-container {
          display: flex;
          align-items: center;
          gap: 12px;
          text-decoration: none;
          color: inherit;
        }

        .landing-stage .logo-badge {
          background: rgba(255, 255, 255, 0.03);
          border: 1px solid rgba(255, 255, 255, 0.08);
          padding: 6px;
          border-radius: 10px;
          display: flex;
          align-items: center;
          justify-content: center;
        }

        .landing-stage .logo-title {
          font-size: 13px;
          font-weight: 800;
          letter-spacing: 0.15em;
          text-transform: uppercase;
        }

        .landing-stage .logo-sub {
          font-size: 10px;
          color: var(--stage-muted);
          font-weight: 500;
        }

        .landing-stage .nav-links {
          display: flex;
          list-style: none;
          gap: 32px;
          margin: 0;
          padding: 0;
        }

        @media (max-width: 900px) {
          .landing-stage .nav-links {
            display: none;
          }
        }

        .landing-stage .nav-links a {
          color: var(--stage-muted);
          text-decoration: none;
          font-size: 14px;
          font-weight: 500;
          transition: color 0.3s;
        }

        .landing-stage .nav-links a:hover {
          color: var(--stage-ink);
        }

        .landing-stage .btn-launch {
          background: #ffffff;
          color: #000000;
          border: none;
          padding: 10px 20px;
          border-radius: 12px;
          font-size: 12px;
          font-weight: 700;
          letter-spacing: 0.05em;
          text-transform: uppercase;
          cursor: pointer;
          transition: transform 0.2s, box-shadow 0.2s;
          display: flex;
          align-items: center;
          gap: 8px;
        }

        .landing-stage .btn-launch:hover {
          transform: translateY(-1px);
          box-shadow: 0 4px 20px rgba(255, 255, 255, 0.15);
        }

        @media (max-width: 900px) {
          .landing-stage .btn-launch-header {
            display: none;
          }
        }

        .landing-stage .burger-btn {
          display: none;
          background: transparent;
          border: none;
          cursor: pointer;
          color: var(--stage-ink);
        }

        @media (max-width: 900px) {
          .landing-stage .burger-btn {
            display: block;
          }
        }

        /* Centered Hero Layout */
        .landing-stage .hero-section {
          padding-top: 160px;
          padding-bottom: 80px;
          max-width: 1000px;
          margin: 0 auto;
          text-align: center;
          padding-left: 24px;
          padding-right: 24px;
          position: relative;
          z-index: 10;
          display: flex;
          flex-direction: column;
          align-items: center;
        }

        .landing-stage .hero-badge {
          background: rgba(139, 92, 246, 0.05);
          border: 1px solid rgba(139, 92, 246, 0.25);
          color: #a78bfa;
          padding: 6px 14px;
          border-radius: 999px;
          font-size: 11px;
          font-weight: 700;
          text-transform: uppercase;
          letter-spacing: 0.1em;
          display: inline-flex;
          align-items: center;
          gap: 6px;
          margin-bottom: 28px;
          animation: rise 0.8s cubic-bezier(.22, 1, .36, 1) both;
        }

        .landing-stage .hero-title {
          font-size: 64px;
          font-weight: 800;
          line-height: 1.1;
          letter-spacing: -0.03em;
          margin: 0 0 24px 0;
          background: linear-gradient(135deg, #ffffff 0%, #a1a1aa 100%);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          max-width: 850px;
          animation: rise 0.9s cubic-bezier(.22, 1, .36, 1) 0.06s both;
        }

        @media (max-width: 768px) {
          .landing-stage .hero-title {
            font-size: 42px;
          }
        }

        .landing-stage .hero-description {
          font-size: 19px;
          line-height: 1.6;
          color: var(--stage-muted);
          margin: 0 0 36px 0;
          max-width: 700px;
          animation: rise 0.9s cubic-bezier(.22, 1, .36, 1) 0.14s both;
        }

        .landing-stage .hero-ctas {
          display: flex;
          gap: 16px;
          margin-bottom: 64px;
          animation: rise 0.9s cubic-bezier(.22, 1, .36, 1) 0.22s both;
        }

        @media (max-width: 480px) {
          .landing-stage .hero-ctas {
            flex-direction: column;
            width: 100%;
          }
          .landing-stage .hero-ctas button,
          .landing-stage .hero-ctas a {
            width: 100%;
          }
        }

        .landing-stage .btn-primary {
          background: #ffffff;
          color: #000000;
          border: none;
          padding: 14px 28px;
          border-radius: 14px;
          font-size: 13px;
          font-weight: 700;
          cursor: pointer;
          transition: transform 0.2s, box-shadow 0.2s;
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 8px;
        }

        .landing-stage .btn-primary:hover {
          transform: translateY(-1px);
          box-shadow: 0 6px 24px rgba(255, 255, 255, 0.2);
        }

        .landing-stage .btn-secondary {
          background: rgba(255, 255, 255, 0.03);
          border: 1px solid rgba(255, 255, 255, 0.08);
          color: var(--stage-ink);
          padding: 14px 28px;
          border-radius: 14px;
          font-size: 13px;
          font-weight: 600;
          cursor: pointer;
          transition: background 0.3s, border-color 0.3s;
          display: flex;
          align-items: center;
          justify-content: center;
          gap: 8px;
          text-decoration: none;
        }

        .landing-stage .btn-secondary:hover {
          background: rgba(255, 255, 255, 0.08);
          border-color: rgba(255, 255, 255, 0.15);
        }

        /* SaaS Product Mockup Preview */
        .landing-stage .product-preview-container {
          width: 100%;
          max-width: 960px;
          background: rgba(255, 255, 255, 0.015);
          border: 1px solid rgba(255, 255, 255, 0.06);
          border-radius: 20px;
          padding: 6px;
          box-shadow: 0 30px 70px rgba(0, 0, 0, 0.8), inset 0 1px 0 rgba(255, 255, 255, 0.05);
          position: relative;
          z-index: 10;
          animation: rise 1s cubic-bezier(.22, 1, .36, 1) 0.3s both;
        }

        .landing-stage .product-preview-inner {
          background: #080808;
          border-radius: 14px;
          overflow: hidden;
          aspect-ratio: 16 / 10;
          display: grid;
          grid-template-rows: 40px 1fr;
          border: 1px solid rgba(255, 255, 255, 0.03);
        }

        .landing-stage .preview-titlebar {
          background: #0e0e0e;
          border-bottom: 1px solid rgba(255, 255, 255, 0.03);
          display: flex;
          align-items: center;
          justify-content: space-between;
          padding: 0 16px;
        }

        .landing-stage .preview-dots {
          display: flex;
          gap: 6px;
        }

        .landing-stage .preview-dot {
          width: 8px;
          height: 8px;
          border-radius: 50%;
          background: rgba(255, 255, 255, 0.15);
        }

        .landing-stage .preview-address {
          background: rgba(255, 255, 255, 0.03);
          border: 1px solid rgba(255, 255, 255, 0.05);
          font-size: 10px;
          color: rgba(255, 255, 255, 0.3);
          padding: 3px 24px;
          border-radius: 6px;
          font-family: monospace;
        }

        .landing-stage .preview-content {
          padding: 24px;
          display: grid;
          grid-template-columns: 1.8fr 1.2fr;
          gap: 20px;
          background-size: 30px 30px;
          background-image: 
            linear-gradient(to right, rgba(255, 255, 255, 0.005) 1px, transparent 1px),
            linear-gradient(to bottom, rgba(255, 255, 255, 0.005) 1px, transparent 1px);
        }

        @media (max-width: 640px) {
          .landing-stage .preview-content {
            grid-template-columns: 1fr;
            padding: 12px;
            gap: 12px;
          }
        }

        .landing-stage .preview-panel {
          background: rgba(255, 255, 255, 0.01);
          border: 1px solid rgba(255, 255, 255, 0.04);
          border-radius: 12px;
          padding: 16px;
          display: flex;
          flex-direction: column;
          justify-content: space-between;
          position: relative;
        }

        .landing-stage .preview-search-box {
          background: rgba(0, 0, 0, 0.4);
          border: 1px solid rgba(255, 255, 255, 0.05);
          border-radius: 8px;
          padding: 10px;
          font-size: 10.5px;
          color: rgba(255, 255, 255, 0.4);
          display: flex;
          align-items: center;
          justify-content: space-between;
          margin-bottom: 20px;
        }

        .landing-stage .preview-flow-graph {
          flex: 1;
          display: flex;
          align-items: center;
          justify-content: space-around;
          position: relative;
          padding: 20px 0;
        }

        .landing-stage .preview-node {
          background: rgba(255, 255, 255, 0.02);
          border: 1px solid rgba(255, 255, 255, 0.08);
          padding: 10px;
          border-radius: 8px;
          display: flex;
          align-items: center;
          justify-content: center;
          z-index: 2;
        }

        .landing-stage .preview-node.active {
          border-color: var(--accent-purple);
          box-shadow: 0 0 10px rgba(139, 92, 246, 0.2);
          background: rgba(139, 92, 246, 0.05);
        }

        .landing-stage .preview-terminal {
          background: rgba(0, 0, 0, 0.5);
          border: 1px solid rgba(255, 255, 255, 0.03);
          border-radius: 10px;
          font-family: monospace;
          padding: 12px;
          font-size: 9.5px;
          display: flex;
          flex-direction: column;
          gap: 8px;
          height: 100%;
        }

        /* Sequential Pipeline visualizer in section 1 */
        .landing-stage .pipeline-container {
          background: rgba(255, 255, 255, 0.015);
          border: 1px solid rgba(255, 255, 255, 0.04);
          border-radius: 20px;
          padding: 40px;
          margin-top: 48px;
        }

        .landing-stage .pipeline-flow {
          display: flex;
          align-items: center;
          justify-content: space-between;
          position: relative;
          gap: 16px;
        }

        @media (max-width: 900px) {
          .landing-stage .pipeline-flow {
            flex-direction: column;
            gap: 40px;
          }
        }

        .landing-stage .pipeline-step {
          flex: 1;
          background: rgba(0, 0, 0, 0.2);
          border: 1px solid rgba(255, 255, 255, 0.03);
          border-radius: 16px;
          padding: 24px;
          position: relative;
          z-index: 2;
          transition: border-color 0.3s;
        }

        .landing-stage .pipeline-step:hover {
          border-color: rgba(255, 255, 255, 0.1);
        }

        .landing-stage .pipeline-icon-box {
          width: 42px;
          height: 42px;
          border-radius: 10px;
          background: rgba(255, 255, 255, 0.03);
          border: 1px solid rgba(255, 255, 255, 0.06);
          display: flex;
          align-items: center;
          justify-content: center;
          margin-bottom: 16px;
        }

        .landing-stage .pipeline-connector {
          flex: 0.3;
          height: 1px;
          background: linear-gradient(to right, rgba(255,255,255,0.05), rgba(255,255,255,0.05));
          position: relative;
        }

        @media (max-width: 900px) {
          .landing-stage .pipeline-connector {
            width: 1px;
            height: 24px;
          }
        }

        .landing-stage .pipeline-connector::after {
          content: '';
          position: absolute;
          width: 4px;
          height: 4px;
          border-radius: 50%;
          background: var(--accent-purple);
          left: 0;
          top: -1.5px;
          animation: runConnector 2s infinite linear;
        }

        @media (max-width: 900px) {
          .landing-stage .pipeline-connector::after {
            left: -1.5px;
            top: 0;
            animation: runConnectorY 2s infinite linear;
          }
        }

        @keyframes runConnector {
          0% { left: 0%; opacity: 0.1; }
          50% { opacity: 1; }
          100% { left: 100%; opacity: 0.1; }
        }

        @keyframes runConnectorY {
          0% { top: 0%; opacity: 0.1; }
          50% { opacity: 1; }
          100% { top: 100%; opacity: 0.1; }
        }

        /* Generic Section design */
        .landing-stage .info-section {
          padding: 100px 40px;
          max-width: 1200px;
          margin: 0 auto;
          position: relative;
          z-index: 10;
          border-top: 1px solid rgba(255, 255, 255, 0.03);
        }

        @media (max-width: 768px) {
          .landing-stage .info-section {
            padding: 70px 20px;
          }
        }

        .landing-stage .section-eyebrow {
          color: var(--accent-purple);
          font-size: 11px;
          font-weight: 800;
          text-transform: uppercase;
          letter-spacing: 0.15em;
          display: block;
          margin-bottom: 12px;
        }

        .landing-stage .section-header-title {
          font-size: 34px;
          font-weight: 800;
          margin: 0 0 20px 0;
          letter-spacing: -0.01em;
        }

        .landing-stage .section-header-desc {
          color: var(--stage-muted);
          font-size: 16px;
          line-height: 1.6;
          max-width: 700px;
          margin: 0 0 48px 0;
        }

        /* Features cards */
        .landing-stage .features-layout-grid {
          display: grid;
          grid-template-cols: repeat(auto-fit, minmax(260px, 1fr));
          gap: 24px;
        }

        .landing-stage .feature-item-card {
          background: rgba(255, 255, 255, 0.015);
          border: 1px solid rgba(255, 255, 255, 0.04);
          border-radius: 16px;
          padding: 32px;
          transition: all 0.3s;
        }

        .landing-stage .feature-item-card:hover {
          border-color: rgba(255, 255, 255, 0.12);
          background: rgba(255, 255, 255, 0.025);
          transform: translateY(-2px);
        }

        .landing-stage .feature-item-num {
          font-size: 12px;
          font-weight: 800;
          color: rgba(255, 255, 255, 0.2);
          margin-bottom: 20px;
          display: block;
        }

        .landing-stage .feature-item-title {
          font-size: 18px;
          font-weight: 700;
          margin: 0 0 12px 0;
        }

        .landing-stage .feature-item-desc {
          color: var(--stage-muted);
          font-size: 14px;
          line-height: 1.6;
          margin: 0;
        }

        /* FAQ accordions */
        .landing-stage .faq-layout-box {
          max-width: 800px;
          display: flex;
          flex-direction: column;
          gap: 16px;
        }

        .landing-stage .faq-accordion-item {
          background: rgba(255, 255, 255, 0.015);
          border: 1px solid rgba(255, 255, 255, 0.04);
          border-radius: 14px;
          overflow: hidden;
          transition: border-color 0.3s;
        }

        .landing-stage .faq-accordion-item:hover {
          border-color: rgba(255, 255, 255, 0.1);
        }

        .landing-stage .faq-accordion-trigger {
          width: 100%;
          background: transparent;
          border: none;
          color: inherit;
          padding: 20px 24px;
          display: flex;
          justify-content: space-between;
          align-items: center;
          font-size: 16px;
          font-weight: 700;
          text-align: left;
          cursor: pointer;
        }

        .landing-stage .faq-accordion-icon {
          color: var(--stage-muted);
          transition: transform 0.3s;
        }

        .landing-stage .faq-accordion-icon.rotated {
          transform: rotate(180deg);
        }

        .landing-stage .faq-accordion-content {
          padding: 0 24px 20px 24px;
          color: var(--stage-muted);
          font-size: 14.5px;
          line-height: 1.6;
          animation: fadeFaqContent 0.2s ease forwards;
        }

        @keyframes fadeFaqContent {
          from { opacity: 0; transform: translateY(-4px); }
          to { opacity: 1; transform: translateY(0); }
        }

        /* Form styling */
        .landing-stage .inquiry-form-card {
          background: rgba(255, 255, 255, 0.015);
          border: 1px solid rgba(255, 255, 255, 0.04);
          border-radius: 20px;
          padding: 40px;
          max-width: 600px;
        }

        @media (max-width: 640px) {
          .landing-stage .inquiry-form-card {
            padding: 24px;
          }
        }

        .landing-stage .form-group {
          display: flex;
          flex-direction: column;
          gap: 8px;
          margin-bottom: 20px;
        }

        .landing-stage .form-label {
          font-size: 11px;
          text-transform: uppercase;
          letter-spacing: 0.1em;
          font-weight: 700;
          color: var(--stage-muted);
        }

        .landing-stage .form-input,
        .landing-stage .form-textarea {
          background: rgba(0, 0, 0, 0.3);
          border: 1px solid rgba(255, 255, 255, 0.05);
          color: var(--stage-ink);
          border-radius: 12px;
          padding: 14px;
          font-size: 13.5px;
          font-family: inherit;
          outline: none;
          transition: border-color 0.3s;
        }

        .landing-stage .form-input:focus,
        .landing-stage .form-textarea:focus {
          border-color: rgba(255, 255, 255, 0.25);
        }

        .landing-stage .form-textarea {
          min-height: 120px;
          resize: vertical;
        }

        .landing-stage .success-card {
          display: flex;
          flex-direction: column;
          align-items: center;
          text-align: center;
          gap: 16px;
          padding: 20px 0;
          animation: fadeLogLine 0.3s ease;
        }

        .landing-stage .success-icon-badge {
          background: rgba(16, 185, 129, 0.1);
          border: 1px solid rgba(16, 185, 129, 0.3);
          padding: 16px;
          border-radius: 50%;
          color: #34d399;
          display: flex;
        }

        /* Footer styling */
        .landing-stage footer.site-foot {
          border-top: 1px solid rgba(255, 255, 255, 0.03);
          padding: 60px 40px;
          background: #010101;
          position: relative;
          z-index: 10;
        }

        @media (max-width: 768px) {
          .landing-stage footer.site-foot {
            padding: 40px 20px;
          }
        }

        .landing-stage .foot-inner {
          max-width: 1200px;
          margin: 0 auto;
          display: flex;
          justify-content: space-between;
          align-items: center;
          flex-wrap: wrap;
          gap: 24px;
        }

        @media (max-width: 640px) {
          .landing-stage .foot-inner {
            flex-direction: column;
            text-align: center;
          }
        }

        .landing-stage .foot-logo-brand {
          font-size: 11px;
          font-weight: 850;
          letter-spacing: 0.15em;
          text-transform: uppercase;
        }

        .landing-stage .foot-telemetry {
          display: flex;
          gap: 24px;
          font-size: 11px;
          color: var(--stage-muted);
          font-weight: 500;
        }

        @media (max-width: 640px) {
          .landing-stage .foot-telemetry {
            flex-direction: column;
            gap: 12px;
          }
        }

        /* Mobile full-bleed overlay menu */
        .landing-stage .mobile-overlay-menu {
          position: fixed;
          inset: 0;
          background: rgba(3, 3, 3, 0.95);
          backdrop-filter: blur(20px);
          -webkit-backdrop-filter: blur(20px);
          z-index: 999;
          opacity: 0;
          visibility: hidden;
          transition: all 0.3s cubic-bezier(0.16, 1, 0.3, 1);
          display: flex;
          flex-direction: column;
          justify-content: center;
          padding: 40px;
        }

        .landing-stage.is-open .mobile-overlay-menu {
          opacity: 1;
          visibility: visible;
        }

        .landing-stage .mobile-links-list {
          list-style: none;
          padding: 0;
          margin: 0 0 40px 0;
          display: flex;
          flex-direction: column;
          gap: 24px;
        }

        .landing-stage .mobile-links-list a {
          color: var(--stage-ink);
          text-decoration: none;
          font-size: 28px;
          font-weight: 800;
        }

        .landing-stage .mobile-overlay-menu button {
          width: 100%;
        }

        /* Load Animations */
        @keyframes rise {
          from {
            opacity: 0;
            transform: translateY(20px);
          }
          to {
            opacity: 1;
            transform: translateY(0);
          }
        }
      ` }} />

      {/* Main Top Nav Bar */}
      <header className="top-nav">
        <a className="logo-container" href="#" onClick={(e) => { e.preventDefault(); setIsOpen(false); }}>
          <div className="logo-badge">
            <BrainCircuit className="w-5 h-5 text-white" />
          </div>
          <div>
            <h1 className="logo-title">Swarm Engine</h1>
            <span className="logo-sub">Autonomous Orchestrator</span>
          </div>
        </a>

        <ul className="nav-links">
          <li><a href="#about">About</a></li>
          <li><a href="#pipeline">Swarm Workflow</a></li>
          <li><a href="#features">Features</a></li>
          <li><a href="#faq">FAQ</a></li>
          <li><a href="#contact">Contact</a></li>
        </ul>

        <button className="btn-launch btn-launch-header" onClick={onLaunch}>
          <span>Launch Platform</span>
          <ArrowRight className="w-3.5 h-3.5" />
        </button>

        <button className="burger-btn" onClick={() => setIsOpen(!isOpen)} aria-label="Toggle Menu">
          <Activity className="w-6 h-6" />
        </button>
      </header>

      {/* Mobile Nav Overlay */}
      <nav className="mobile-overlay-menu">
        <ul className="mobile-links-list">
          <li><a href="#about" onClick={() => setIsOpen(false)}>About</a></li>
          <li><a href="#pipeline" onClick={() => setIsOpen(false)}>Swarm Workflow</a></li>
          <li><a href="#features" onClick={() => setIsOpen(false)}>Features</a></li>
          <li><a href="#faq" onClick={() => setIsOpen(false)}>FAQ</a></li>
          <li><a href="#contact" onClick={() => setIsOpen(false)}>Contact</a></li>
        </ul>
        <button className="btn-primary" onClick={() => { setIsOpen(false); onLaunch(); }}>
          <span>Launch Platform</span>
          <ArrowRight className="w-4 h-4" />
        </button>
      </nav>

      {/* Hero section with grid backdrop */}
      <div className="obsidian-grid relative overflow-hidden">
        <div className="spotlight" style={{ top: '10%', left: '50%', transform: 'translateX(-50%)' }} />

        <div className="hero-section">
          <div className="hero-badge">
            <Sparkles className="w-3.5 h-3.5" />
            <span>Autonomous Swarms v1.0.0</span>
          </div>
          
          <h2 className="hero-title">
            Orchestrate Intelligence, Verified in Real-Time
          </h2>
          
          <p className="hero-description">
            Deconstruct complex queries, execute parallel web audits, and compile peerless, publication-grade knowledge bases automatically.
          </p>
          
          <div className="hero-ctas">
            <button className="btn-primary" onClick={onLaunch}>
              <span>Launch Research Console</span>
              <ArrowRight className="w-4 h-4" />
            </button>
            <a href="#pipeline" className="btn-secondary">
              <span>Explore Workflow</span>
            </a>
          </div>

          {/* High-Fidelity SaaS UI Mockup Preview */}
          <div className="product-preview-container">
            <div className="product-preview-inner">
              
              <div className="preview-titlebar">
                <div className="preview-dots">
                  <div className="preview-dot" />
                  <div className="preview-dot" />
                  <div className="preview-dot" />
                </div>
                <div className="preview-address">swarm-console.engine</div>
                <div className="w-8" />
              </div>
              
              <div className="preview-content">
                <div className="preview-panel">
                  <div className="preview-search-box">
                    <span>Describe your research target...</span>
                    <Terminal className="w-3 h-3 text-zinc-500" />
                  </div>
                  
                  {/* Miniature Agent Flow Representation */}
                  <div className="preview-flow-graph">
                    <div className="preview-node active">
                      <BrainCircuit className="w-3.5 h-3.5 text-purple-400 mr-1.5" />
                      <span className="text-[9px] font-bold">Supervisor</span>
                    </div>
                    <div className="w-6 h-px bg-zinc-800" />
                    <div className="preview-node">
                      <Search className="w-3.5 h-3.5 text-blue-400 mr-1.5" />
                      <span className="text-[9px] font-bold">Researcher</span>
                    </div>
                  </div>
                </div>
                
                <div className="preview-terminal">
                  <span className="text-zinc-600 font-bold">[19:55:01] pipeline-start</span>
                  <span className="text-zinc-400">Node [Supervisor] active. Planning traversal targets...</span>
                  <span className="text-zinc-500">Node [Researcher] standby. Waiting for parameters.</span>
                </div>
              </div>

            </div>
          </div>
        </div>
      </div>

      {/* About Section */}
      <section id="about" className="info-section">
        <span className="section-eyebrow">01 / Swarm Core</span>
        <h3 className="section-header-title">Engineered to deconstruct & verify domain knowledge</h3>
        <p className="section-header-desc">
          The Autonomous Research Engine operates as a decentralized network of specialized nodes. By separating tasks between planning, content scraping, consistency audits, and report formatting, the platform reduces analysis timelines from days to seconds while targeting hallucination vectors.
        </p>

        <div className="features-layout-grid" style={{ gridTemplateColumns: '1fr 1fr', gap: '48px' }}>
          <div>
            <h4 style={{ fontSize: '18px', fontWeight: 800, margin: '0 0 16px 0' }}>Decoupled Processing Loop</h4>
            <p style={{ color: 'var(--stage-muted)', fontSize: '14.5px', lineHeight: 1.6, margin: 0 }}>
              Traditional single-agent scripts struggle with recursion loops. By breaking execution down into discrete stages with strict state interfaces, each agent coordinates on its specific mandate, ensuring high-density facts.
            </p>
          </div>
          <div>
            <h4 style={{ fontSize: '18px', fontWeight: 800, margin: '0 0 16px 0' }}>Hallucination Mitigation Protocol</h4>
            <p style={{ color: 'var(--stage-muted)', fontSize: '14.5px', lineHeight: 1.6, margin: 0 }}>
              The Critic node enforces strict documentation alignment. Every claim generated by the pipeline is checked back against scraped index databases. If a verification criteria is not satisfied, the loop automatically directs Researcher agents back to Tavily to crawl supplementary facts.
            </p>
          </div>
        </div>
      </section>

      {/* Pipeline workflow visualizer */}
      <section id="pipeline" className="info-section">
        <span className="section-eyebrow">02 / Workflow Pipeline</span>
        <h3 className="section-header-title">Sequential Swarm Coordination</h3>
        <p className="section-header-desc">
          The research loop coordinates agents sequentially to ingest, cross-reference, and format knowledge.
        </p>

        <div className="pipeline-container">
          <div className="pipeline-flow">
            {/* Step 1 */}
            <div className="pipeline-step">
              <div className="pipeline-icon-box" style={{ color: '#8b5cf6' }}>
                <BrainCircuit className="w-5 h-5" />
              </div>
              <h4 style={{ fontSize: '15px', fontWeight: 700, margin: '0 0 8px 0' }}>1. Planning</h4>
              <p style={{ color: 'var(--stage-muted)', fontSize: '12.5px', lineHeight: 1.5, margin: 0 }}>
                Supervisor parses input targets, creating structured research objectives.
              </p>
            </div>
            
            <div className="pipeline-connector" />

            {/* Step 2 */}
            <div className="pipeline-step">
              <div className="pipeline-icon-box" style={{ color: '#3b82f6' }}>
                <Search className="w-5 h-5" />
              </div>
              <h4 style={{ fontSize: '15px', fontWeight: 700, margin: '0 0 8px 0' }}>2. Gathering</h4>
              <p style={{ color: 'var(--stage-muted)', fontSize: '12.5px', lineHeight: 1.5, margin: 0 }}>
                Researcher performs concurrent crawls on Tavily API to gather data.
              </p>
            </div>

            <div className="pipeline-connector" />

            {/* Step 3 */}
            <div className="pipeline-step">
              <div className="pipeline-icon-box" style={{ color: '#f4f4f5' }}>
                <ShieldCheck className="w-5 h-5" />
              </div>
              <h4 style={{ fontSize: '15px', fontWeight: 700, margin: '0 0 8px 0' }}>3. Auditing</h4>
              <p style={{ color: 'var(--stage-muted)', fontSize: '12.5px', lineHeight: 1.5, margin: 0 }}>
                Critic node validates scraped text against facts, filtering assumptions.
              </p>
            </div>

            <div className="pipeline-connector" />

            {/* Step 4 */}
            <div className="pipeline-step">
              <div className="pipeline-icon-box" style={{ color: '#10b981' }}>
                <FileText className="w-5 h-5" />
              </div>
              <h4 style={{ fontSize: '15px', fontWeight: 700, margin: '0 0 8px 0' }}>4. Assembly</h4>
              <p style={{ color: 'var(--stage-muted)', fontSize: '12.5px', lineHeight: 1.5, margin: 0 }}>
                Synthesizer compiles finalized, publication-grade Markdown reports.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Features Grid Section */}
      <section id="features" className="info-section">
        <span className="section-eyebrow">03 / Platform Specs</span>
        <h3 className="section-header-title">The Swarm Node Specifications</h3>
        <p className="section-header-desc">
          Specialized nodes running concurrently to compile facts.
        </p>

        <div className="features-layout-grid">
          {/* Card 1 */}
          <div className="feature-item-card">
            <span className="feature-item-num">01 / Supervisor</span>
            <h4 className="feature-item-title">Supervisor Node</h4>
            <p className="feature-item-desc">
              Parses the research objective, maps target query trajectories, coordinates graph states, and supervises loop execution.
            </p>
          </div>
          {/* Card 2 */}
          <div className="feature-item-card">
            <span className="feature-item-num">02 / Researcher</span>
            <h4 className="feature-item-title">Researcher Node</h4>
            <p className="feature-item-desc">
              Executes concurrent searches across scientific literature, news hubs, and databases using optimized Tavily scrapers.
            </p>
          </div>
          {/* Card 3 */}
          <div className="feature-item-card">
            <span className="feature-item-num">03 / Critic</span>
            <h4 className="feature-item-title">Critic Node</h4>
            <p className="feature-item-desc">
              Cross-references claims with scraped source fragments, audits logical consistency, and enforces verification limits.
            </p>
          </div>
          {/* Card 4 */}
          <div className="feature-item-card">
            <span className="feature-item-num">04 / Synthesizer</span>
            <h4 className="feature-item-title">Synthesizer Node</h4>
            <p className="feature-item-desc">
              Reconciles conflicting perspectives, resolves semantic gaps, formatting finalized reports into crisp Markdown docs.
            </p>
          </div>
        </div>
      </section>

      {/* FAQ Section */}
      <section id="faq" className="info-section">
        <span className="section-eyebrow">04 / FAQ</span>
        <h3 className="section-header-title">Frequently Asked Questions</h3>
        <p className="section-header-desc">
          Everything you need to know about the engine's capabilities and operations.
        </p>

        <div className="faq-layout-box">
          {FAQS.map((faq, index) => (
            <div className="faq-accordion-item" key={index}>
              <button 
                className="faq-accordion-trigger" 
                onClick={() => setActiveFaq(activeFaq === index ? null : index)}
              >
                <span>{faq.q}</span>
                <ChevronDown className={`w-4 h-4 faq-accordion-icon ${activeFaq === index ? 'rotated' : ''}`} />
              </button>
              {activeFaq === index && (
                <div className="faq-accordion-content">
                  <p style={{ margin: 0 }}>{faq.a}</p>
                </div>
              )}
            </div>
          ))}
        </div>
      </section>

      {/* Contact Section */}
      <section id="contact" className="info-section">
        <span className="section-eyebrow">05 / API Integrations</span>
        <h3 className="section-header-title">Connect Swarms to Your Architecture</h3>
        <p className="section-header-desc">
          Ready to scale custom research pipelines? Connect to enterprise data or coordinate custom LLM models.
        </p>

        <div className="inquiry-form-card">
          {!isSubmitted ? (
            <form onSubmit={handleContactSubmit}>
              <div className="form-group">
                <label className="form-label" htmlFor="email-addr">Email Address</label>
                <input 
                  type="email" 
                  id="email-addr" 
                  placeholder="name@company.com" 
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="form-input" 
                  required 
                />
              </div>
              <div className="form-group">
                <label className="form-label" htmlFor="scope-desc">Scope Description</label>
                <textarea 
                  id="scope-desc" 
                  placeholder="Describe your research scope or API objective..."
                  value={message}
                  onChange={(e) => setMessage(e.target.value)}
                  className="form-textarea" 
                  required
                />
              </div>
              <button type="submit" className="btn-primary" style={{ width: '100%', marginTop: '10px' }}>
                <Mail className="w-4 h-4" />
                <span>Submit API Inquiry</span>
              </button>
            </form>
          ) : (
            <div className="success-card">
              <div className="success-icon-badge">
                <Check className="w-8 h-8" />
              </div>
              <h4 style={{ fontSize: '18px', fontWeight: 800, margin: 0 }}>Inquiry Received</h4>
              <p style={{ color: 'var(--stage-muted)', fontSize: '14px', lineHeight: 1.5, margin: 0 }}>
                Our systems have logged your inquiry parameters. An engineer will coordinate with you via <strong>{email}</strong>.
              </p>
            </div>
          )}
        </div>
      </section>

      {/* Footer */}
      <footer className="site-foot">
        <div className="foot-inner">
          <div className="foot-logo-brand">
            <span>Swarm Engine © {new Date().getFullYear()}</span>
          </div>
          <div className="foot-telemetry">
            <span>Core v1.0.0</span>
            <span>API: Connected</span>
            <span>Engine Status: Nominal</span>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default LandingPage;
